// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://atwqmghvpyawsxeykgpb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF0d3FtZ2h2cHlhd3N4ZXlrZ3BiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1NzM1NzgsImV4cCI6MjA3MTE0OTU3OH0.fob0cnq6VxoIrmRPpaUHH-AcMZNQj3byVNtFJq3CreE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});